### ISSUE TITLE
Improve support and documentation for Grafana Agent Flow mode

### ISSUE THREAD

**Issue by moray95** [grafana/grafana-ansible-collection#130]
Hello,

I have used the Grafana Agent role to install it in flow mode. The presence and documentation for the `grafana_agent_mode` variable implies that the role can easily be configured in flow mode. However, changing the variable causes a variety of issues which are not properly documented and hard to troubleshoot for a newcomer.

1.  None of the [default flags](https://github.com/grafana/grafana-ansible-collection/blob/main/roles/grafana_agent/defaults/main.yaml#L62) are supported in flow mode
2. The [configuration file](https://github.com/grafana/grafana-ansible-collection/blob/main/roles/grafana_agent/templates/config.yaml.j2) is for the static mode and does not work for flow mode (as it requires river configuration).
3. Setting `grafana_agent_provisioned_config_file` to custom config file works around the last issue, but [does not allow for templating](https://github.com/grafana/grafana-ansible-collection/blob/main/roles/grafana_agent/tasks/configure.yaml#L43).

For reference, here is the minimal playbook that works with flow mode:

```yaml
- hosts: all
  tasks:
    - name: Install Grafana Agent
      ansible.builtin.include_role:
        name: grafana.grafana.grafana_agent
      vars:
        grafana_agent_mode: flow
        # Change config file on the host to .river
        grafana_agent_config_filename: config.river
        # Change config file to be copied
        grafana_agent_provisioned_config_file:  "files/config.river"
        # Remove default flags
        grafana_agent_flags_extra:
          server.http.listen-addr: '0.0.0.0:12345'
```
