### ISSUE TITLE
Grafana package can no longer be installer from apt repo https://apt.grafana.com/

### ISSUE THREAD

**Issue by VGerris** [grafana/grafana-ansible-collection#182]
Since today, using the role fails with : 

```bash
TASK [grafana.grafana.grafana : Install Grafana] ****************************************************************************************************************************
fatal: [icinga2test.binero.net]: FAILED! => {"changed": false, "msg": "No package matching 'grafana' is available"}
```
If I look in the packages available, I see grafana-nightly only.
The content of my apt file is :

```bash
root@icinga-server:~# cat /etc/apt/sources.list.d/apt_grafana_com.list 
deb [arch=amd64 signed-by=/usr/share/keyrings/grafana.key] https://apt.grafana.com/ stable main
```
Did something change in the repo ?
This causes my playbook that worked last week to fail.

The install tasks has : **grafana_package** as a variable but it does not work to use that in the playbook.

So the apt is matching the current documentation.

As a workaround I added the following in an Ansible task:

```yaml
    - name: Install grafana via deb because apt repo misses package
      ansible.builtin.apt:
        deb: https://dl.grafana.com/oss/release/grafana_10.4.1_amd64.deb
```
Taken from : https://grafana.com/grafana/download?edition=oss .
This works as a workaround because the package does not need re-installation.

I hope this can be corrected so the playbook works again.
It may be a good idea to implement the **grafana_package** variable if more than 1 package can be installed, so it can be chosen by parameter.
