### ISSUE TITLE
Alloy role - Add user to additional groups

### ISSUE THREAD

**Issue by fkonradmain** [grafana/grafana-ansible-collection#199]
Some logs on linux machines are not readable by anyone. They are either owned by root or another group. For example, on debian based systems, they are owned by the 'adm' group.

It would be great, if we were able to assign the alloy user to those groups using the 'alloy' role of this collection.

I am looking forward to your responses to that topic. Thank you very much!

**Comment by fkonradmain** [comment]
Hi @ishanjainn and thank you for the quick response.

According to the ansible documentation, that would only set the primary group. -> [ansible.builtin.user](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/user_module.html#parameter-group)

When we want to add the user to additional groups, we would have to use the `groups` statement.

Currently, this parameter is not set:

[install.yml, Line 13](https://github.com/grafana/grafana-ansible-collection/blob/main/roles/alloy/tasks/install.yml#L13)
```yml
- name: Create alloy user
  ansible.builtin.user:
    name: "{{ service_user }}"
    group: "{{ service_group }}"
    system: true
    create_home: false  # Appropriate for a system user, usually doesn't need a home directory
  become:  #true
```
