### ISSUE TITLE
Declare Module default groups

### ISSUE THREAD

**Issue by Derioss** [grafana/grafana-ansible-collection#224]
(Official doc)[https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_module_defaults.html]

Hello !

it's very nice to declare group in meta/runtime.yml for remove some duplicate code in ansible tasks.

for example:

```YAML
- name: Usage of module is_default
  module_defaults:
    group/grafana:
      grafana_url: "https://{{ monitoring_grafana_server_name }}"
      grafana_user: "{{ monitoring_grafana_user }}"
      grafana_password: "{{ monitoring_grafana_pass }}"
      use_proxy: false
      validate_certs: false
  block:
    - name: Add prometheus datasource
      community.grafana.grafana_datasource:
        name: prometheus
        ds_type: prometheus
        access: direct
        is_default: true
        ds_url: http://prometheus:9090

    - name: Load grafana dashboard
      community.grafana.grafana_dashboard:
        folder: "{{ item.folder }}"
        dashboard_id: "{{ item.dashboard_id }}"
        dashboard_revision: "{{ item.dashboard_revision }}"
```
