### ISSUE TITLE
alloy: Restart the service when version is changed

### ISSUE THREAD

**Issue by f9n** [grafana/grafana-ansible-collection#233]
When we change the version (1.0.0 -> 1.2.0), role does not restart the `alloy` service. Is this normal? Or can we support restarting when version changes?

```yaml
# roles/alloy/tasks/install.yml
...
- name: Download alloy binary
  ansible.builtin.get_url:
    url: "{{ binary_url }}"
    dest: "/tmp/alloy-{{ version }}.zip"
    mode: '0755'
  become: true

- name: Extract alloy binary
  ansible.builtin.unarchive:
    src: "/tmp/alloy-{{ version }}.zip"
    dest: "/tmp"
    remote_src: yes
  become: true

- name: Copy installed binary to installation dir
  ansible.builtin.copy:
    src: "/tmp/alloy-linux-{{ arch }}"
    dest: "{{ installation_dir }}/alloy-linux-{{ arch }}"
    mode: '0755'
    remote_src: yes
  become: true
  notify: Restart alloy
```
If it is convenient for you, we can create a pull request for the above changes.
cc: @emre-23 @acciorg
