### ISSUE TITLE
dnf issues with granfa repo

### ISSUE THREAD

**Issue by Dialgatrainer02** [grafana/grafana-ansible-collection#236]
dnf fails to update after grafana.grafana.grafana module runs its get to installing grafana and dies 

```
TASK [grafana.grafana.grafana : Install Grafana] **************************************************************************************************************************************************************************************************************
fatal: [grafana]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 192.168.0.102 closed.\r\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 137}
```
heres what happens if i try to do it manually
```
[root@vault3-test ~]# ls /etc/yum.repos.d/
almalinux-appstream.repo  almalinux-crb.repo     almalinux-highavailability.repo  almalinux-plus.repo              almalinux-rt.repo       almalinux-sap.repo
almalinux-baseos.repo     almalinux-extras.repo  almalinux-nfv.repo               almalinux-resilientstorage.repo  almalinux-saphana.repo  grafana.repo
[root@vault3-test ~]# dnf update -vvvv
Loaded plugins: builddep, changelog, config-manager, copr, debug, debuginfo-install, download, generate_completion_cache, groups-manager, needs-restarting, playground, repoclosure, repodiff, repograph, repomanage, reposync, system-upgrade
DNF version: 4.14.0
cachedir: /var/cache/dnf
User-Agent: constructed: 'libdnf (AlmaLinux 9.4; generic; Linux.x86_64)'
repo: using cache for: appstream
appstream: using metadata from Wed 03 Jul 2024 02:48:54 PM UTC.
repo: using cache for: baseos
baseos: using metadata from Wed 03 Jul 2024 02:49:25 PM UTC.
repo: using cache for: extras
extras: using metadata from Wed 03 Jul 2024 02:49:45 PM UTC.
repo: using cache for: grafana
Killed
[root@vault3-test ~]# dnf install grafana -vvvv
Loaded plugins: builddep, changelog, config-manager, copr, debug, debuginfo-install, download, generate_completion_cache, groups-manager, needs-restarting, playground, repoclosure, repodiff, repograph, repomanage, reposync, system-upgrade
DNF version: 4.14.0
cachedir: /var/cache/dnf
User-Agent: constructed: 'libdnf (AlmaLinux 9.4; generic; Linux.x86_64)'
repo: using cache for: appstream
appstream: using metadata from Wed 03 Jul 2024 02:48:54 PM UTC.
repo: using cache for: baseos
baseos: using metadata from Wed 03 Jul 2024 02:49:25 PM UTC.
repo: using cache for: extras
extras: using metadata from Wed 03 Jul 2024 02:49:45 PM UTC.

AlmaLinux 9.4 (Seafoam Ocelot)
Kernel 6.8.4-2-pve on an x86_64

vault3-test login: 
```
after my second time using dnf (and  it erroring) i got logged out
what other logs can i provide? 
im unsure if this is an issue with this role or with dnf 
task used to install grafana
```yml
- name: install and setup granfana
  hosts: grafana
  roles:
    - role: grafana.grafana.grafana
  vars:
    grafana_security:
      admin_user: olivia
      admin_password: testing
    grafana_datasources:
      - name: prometheus
        type: prometheus
        access: proxy
        url: 'http://{{ hostvars["prometheus"].ansible_host | ansible.utils.ipv4 }}:9090'
        basicAuth: false
      - name: loki
        type: loki
        access: proxy
        url: 'http://{{ hostvars["loki"].ansible_host | ansible.utils.ipv4 }}:3100'
        basicAuth: false
  tags:
    - granfana
```
