### ISSUE TITLE
unified alerting not being disabled when version too high

### ISSUE THREAD

**Issue by Dialgatrainer02** [grafana/grafana-ansible-collection#237]
i haven't specified a version when installing grafana. it fails when starting the systemd service and when i check the config 
```ini
# Alerting
[alerting]
enabled = true
execute_alerts = True
```
journalctl -xeu grafana-server
```
Jul 05 21:03:27 vault3-test grafana[3897]: logger=settings t=2024-07-05T21:03:27.518630198Z level=info msg="Starting Grafana" version=11.1.0 commit=5b85c4c2fcf5d32d4f68aaef345c53096359b2f1 branch=HEAD compiled=2024-07-05T21:03:27Z
Jul 05 21:03:27 vault3-test grafana[3897]: logger=settings t=2024-07-05T21:03:27.519095787Z level=error msg="Option '[alerting].enabled' cannot be true. Legacy Alerting is removed. It is no longer deployed, enhanced, or supported. Delete '[alerting].enabled' and use '[unified_alerting].enabled' to enable Grafana Alerting. For more information, refer to the documentation on upgrading to Grafana Alerting (https://grafana.com/docs/grafana/v10.4/alerting/set-up/migrating-alerts)"
Jul 05 21:03:27 vault3-test grafana[3897]: Error: ✗ invalid setting [alerting].enabled
```
this is a fresh install and not an update from version 10.???

**Comment by GDWR** [comment]
This is [a documented breaking change in v11](https://grafana.com/docs/grafana/latest/breaking-changes/breaking-changes-v11-0/#legacy-alerting-is-entirely-removed). 

Due to [the templating](https://github.com/grafana/grafana-ansible-collection/blob/c7c298ab5faa0450195801fc87bae254a439476a/roles/grafana/templates/grafana.ini.j2#L131) the `[alerting].enabled` is set if `grafana_alerting` is anything but  empty/`{}` but [the default](https://github.com/grafana/grafana-ansible-collection/blob/c7c298ab5faa0450195801fc87bae254a439476a/roles/grafana/defaults/main.yml#L184-L185) is `{ execute_alerts: true }` setting the field if you do not override it.

I've just done this in my role for the moment.
```yml
- name: Install Grafana
  hosts: monitoring
  roles:
    - grafana.grafana.grafana
  vars:
    grafana_instance: AbandonTech
    grafana_alerting: {} # https://github.com/grafana/grafana-ansible-collection/issues/237
```

I think the most suitable fix, in terms for this repository, is have different templating based on the version as it that [pattern already seems present in the templating](https://github.com/grafana/grafana-ansible-collection/blob/c7c298ab5faa0450195801fc87bae254a439476a/roles/grafana/templates/grafana.ini.j2#L116).

**Comment by GDWR** [comment]
This is [a documented breaking change in v11](https://grafana.com/docs/grafana/latest/breaking-changes/breaking-changes-v11-0/#legacy-alerting-is-entirely-removed). 

Looks like this has already been fixed in #215 just need to wait on a new tag as its [not in 5.2.0](https://github.com/grafana/grafana-ansible-collection/blob/1fd392ddf3166888ba60689897239e487c4cbbe2/roles/grafana/templates/grafana.ini.j2#L116-L127).

For the moment you could set the variable to `{}`.
```yml
- name: Install Grafana
  hosts: monitoring
  roles:
    - grafana.grafana.grafana
  vars:
    grafana_instance: AbandonTech
    grafana_alerting: {} # Fixed by grafana collection 5.3.0
```
