### ISSUE TITLE
support   `foldersFromFilesStructure`

### ISSUE THREAD

**Issue by copolycube** [grafana/grafana-ansible-collection#277]
https://grafana.com/docs/grafana/latest/administration/provisioning/#dashboards indicate that we can push a structure of dashboards to grafana, but no options in the playbook allows this currently

**Comment by copolycube** [comment]
workaround : 
```
    # https://grafana.com/docs/grafana/latest/administration/provisioning/#dashboards
    # Circumvent / until fix https://github.com/grafana/grafana-ansible-collection/issues/277
    - name: Dashboard provider with foldersFromFilesStructure
      become: true
      ignore_errors: True
      block:
        - name: Ensure grafana provisioning dashboard config directory exist
          ansible.builtin.file:
            path: /etc/grafana/provisioning/dashboards
            state: directory
            mode: '0755'

        - name: Generate grafana provisioning dashboards config file git-versionned-dashboards.yml
          ansible.builtin.copy:
            dest: /etc/grafana/provisioning/dashboards/git-versionned-dashboards.yml
            content: |
              apiVersion: 1
              providers:
              -   name: git-versionned
                  folder: 'git-versionned'
                  options:
                      path: {{ dashboards_dir }}
                      foldersFromFilesStructure: true
                  orgId: 1
                  type: file
            mode: '0644'

        - name: Push whole directory of git git-versionned dashboards
          ansible.builtin.copy:
            src: "dashboards/"
            dest: "{{ dashboards_dir }}"
            mode: "0755"
          become: true

        - name: Set privileges on provisioned dashboards
          ansible.builtin.file:
            path: "{{ dashboards_dir }}"
            recurse: true
            owner: "grafana"
            group: "grafana"
            mode: "0640"
          become: true

        - name: Set privileges on provisioned dashboards directory structure
          ansible.builtin.file:
            path: "{{ dashboards_dir }}"
            state: "directory"
            recurse: true
            mode: "0755"
          become: true
```
