### ISSUE TITLE
Remove Legacy alerting > v11.0.0

### ISSUE THREAD

**Issue by tayfun57** [grafana/grafana-ansible-collection#288]
When installing a grafana version newer than v11.0.0, grafana will not start. 

If you remove the following lines from: roles/grafana/templates/grafana.ini.j2

{% if grafana_version != 'latest' and grafana_version.split('.')[0]|int < 11 %}
# Alerting
[alerting]
{% if grafana_alerting != {} %}
enabled = true
{%   for k,v in grafana_alerting.items() %}
{%     if k != 'enabled' %}
{{ k }} = {{ v }}
{%     endif %}
{%   endfor %}
{% else %}
enabled = false
{% endif %}
{% endif %}

I will work for me. 

Error log:

logger=settings t=2024-11-01T14:26:41.858695142Z level=error msg="Option '[alerting].enabled' cannot be true. Legacy Alerting is removed. It is no longer deployed, enhanced, or supported. Delete '[alerting].enabled' and use '[unified_alerting].enabled' to enable Grafana Alerting. For more information, refer to the documentation on upgrading to Grafana Alerting (https://grafana.com/docs/grafana/v10.4/alerting/set-up/migrating-alerts)"

**Comment by voidquark** [comment]
Could you please confirm that you are using the latest version of the collection?

If your Grafana version is v11 or higher, the template uses [unified_alerting] instead of [alerting]. I’m not sure why you want to remove this part, as the current logic allows for deploying both older and newer versions. The conditional statement simply determines which alerting block to use based on the version:

```
{% if grafana_version == 'latest' or grafana_version.split('.')[0]|int >= 11 %}
# Unified Alerting
[unified_alerting]
.....

{% if grafana_version != 'latest' and grafana_version.split('.')[0]|int < 11 %}
# Alerting
[alerting]
.....
```

**Comment by voidquark** [comment]
@tayfun57 can you confirm above comment ?

**Comment by pbirokas** [comment]
Hello, I just run into the same problem and can confirm this.

This is the playbook I used
```
---
- hosts: XYZABC
  become: true
  roles:
    - grafana.grafana.grafana
  vars:
    grafana_version: latest
    grafana_manage_repo: true
    grafana_use_provisioning: true
    grafana_provisioning_synced: false
    grafana_security:
      admin_user: "admin"
      admin_password: "******************"
    grafana_users:
      allow_sign_up: false
    grafana_datasources:
      - name: "victoriametrics"
        type: "prometheus"
        url: "http://localhost:8428/prometheus"
        isDefault: true
...
```

`Nov 20 14:11:54 XYZABC grafana[3750369]: logger=settings t=2024-11-20T14:11:54.636794093Z level=error msg="Option '[alerting].enabled' cannot be true. Legacy Alerting is  removed. It is no longer deployed, enhanced, or supported. Delete '[alerting].enabled' [...]`

On the system there was allready an collection available, so the "ansible-galaxy collection install grafana.grafana" did not updated it. With an "--force" I got a newer version on my profile.

```
$ ansible-galaxy collection list | grep grafana.grafana
grafana.grafana                          5.6.0
grafana.grafana                          2.2.4

```
After the installation of the newest version, the Playbook worked as expected.
