### ISSUE TITLE
Promtail role. Template doesn't parse promtail_clients

### ISSUE THREAD

**Issue by rmalenko** [grafana/grafana-ansible-collection#305]
In this case `- url: http://11.11.11.11:3100/loki/api/v1/push` `config.yml` creates with `clients:` section
In this case the section `clients` doesn't create `- url: http://{{ loki_private_ip }}:3100/loki/api/v1/push`

```yaml
- name: Deploy promtail to servers
  hosts: loki
  gather_facts: true
  vars:
    loki_private_ip: "{{ hostvars['ams3-loki']['loki_private_ip'] }}"
    loki_domain: "{{ hostvars['ams3-loki'][inventory_hostname]['domain'] }}"
  roles:
    - role: grafana.grafana.promtail
      vars:
        promtail_server:
          http_listen_address: "{{ ansible_facts['eth1']['ipv4']['address'] }}"
          http_listen_port: 9080
        promtail_clients:
          - url: http://11.11.11.11:3100/loki/api/v1/push
          # - url: http://{{ loki_private_ip }}:3100/loki/api/v1/push
        promtail_extra_flags:
          - "-client.external-labels=hostname=%H"
          - "-config.expand-env=true"
```
