### ISSUE TITLE
opentelemetry_collector - template error

### ISSUE THREAD

**Issue by rmalenko** [grafana/grafana-ansible-collection#310]
In ansible role:
```yaml
        otel_collector_processors:
          memory_limiter:
            # 75% of maximum memory up to 1G
            limit_mib: "{{ (ansible_facts['memtotal_mb'] * 0.75) | round | int }}"
            # 25% of limit up to 1G
            spike_limit_mib: "{{ (ansible_facts['memtotal_mb'] * 0.25) | round | int }}"
            check_interval: 5s
```
In config.yaml, we have values with single quotes, which leads to an error at the start.

```yaml
memory_limiter:
  limit_mib: '721'
  spike_limit_mib: '240'
  check_interval: 5s
```

I have changed in `otel_collector.service.j2` 

```jinja
processors:
{{ otel_collector_processors | to_nice_yaml(indent=2) | indent(2, true) }}
{% endif %}
```

to

```jinja
processors:
{{ otel_collector_processors | to_nice_yaml(indent=2) | indent(2, true) | regex_replace("'", "") }}
{% endif %}

```

May someone have a better solutions?
