### ISSUE TITLE
Plugins path on grafana role don't match when modified

### ISSUE THREAD

**Issue by allancalix** [grafana/grafana-ansible-collection#331]
## Summary
Some configuration options interact weird together and result in an installation where the plugins directory from the server doesn't match where plugins get installed by the role. This results in none of the plugins working when these options are set unless the PLUGINS_DIR is fixed.

I'm especially confused because the environment variable in `/etc/default/grafana-server' is set to `PLUGINS_DIR=/var/lib/grafana/plugins` so I have no idea why it's looking in `/user/grafana`.

## How to reproduce
What seems to happen is with the `paths.data` option configured, the plugin installer puts plugins in a `/plugins` directory within the data directory configured but the server expects plugins to exist in the parent directory. I looked around but couldn't find why the server looks up plugins in the parent directory.

https://github.com/grafana/grafana-ansible-collection/blob/42946a514f974f436508c513024c2ebf686e0acd/roles/grafana/defaults/main.yml#L32

https://github.com/grafana/grafana-ansible-collection/blob/42946a514f974f436508c513024c2ebf686e0acd/roles/grafana/tasks/plugins.yml#L13

```yaml
   grafana_env:
      PLUGINS_DIR: /usr/grafana/data/plugins # force the server to look in the right place as workaround

  grafana_ini:
      paths:
        logs: "/user/grafana/logs"
        data: "/user/grafana/data"
```

This is the log line I saw before I set the environment variable. This path doesn't match where plugins are actually installed.

```
logger=settings t=2025-03-04T18:01:34.460857267-08:00 level=info msg="Path Plugins" path=/user/grafana/plugins
```
