### ISSUE TITLE
Ability to enable Grafana metrics

### ISSUE THREAD

**Issue by nickbroon** [grafana/grafana-ansible-collection#332]
It would be useful if the grafana.grafana role had a variable to control the `grafana.ini` option to enable metrics:
``` ini
[metrics]
enabled = true
```

https://grafana.com/docs/grafana/latest/setup-grafana/set-up-grafana-monitoring/#pull-metrics-from-grafana-into-prometheus

As this could then be scraped into promtheus using prometheus ansible role:

``` yaml
prometheus_scrape_configs:
- job_name: "prometheus"
  metrics_path: "/metrics"
  static_configs:
  - targets:
    - "{{ ansible_host }}:9090"
- job_name: "grafana"
  static_configs:
  - targets:
    - "{{ ansible_host }}:3000"
```

**Comment by intermittentnrg** [comment]
provide variable to the role, something like:
```yaml
- hosts: all
  roles:
    - role: grafana.grafana.grafana
      vars:
        grafana_ini:
          metrics:
            enabled: true
```
