### ISSUE TITLE
Overwriting dashboards doesn't work anymore

### ISSUE THREAD

**Issue by Lusitaniae** [grafana/grafana-ansible-collection#338]
Please see issues https://github.com/grafana/grafana/pull/97011 https://github.com/grafana/grafana/pull/90687

Dashboard names are no longer unique so when I try to import a dashboard like this

```
- name: Import Grafana dashboard foo
  community.grafana.grafana_dashboard:
    grafana_url: http://grafana.company.com
    grafana_api_key: "{{ grafana_api_key }}"
    state: present
    commit_message: Updated by ansible
    overwrite: true
    path: /path/to/dashboards/foo.json
```

It will just create a new one with different UID

Guessing we'll need to use the UID param when state: present too

```
uid 
string

added in community.grafana 1.0.0

uid of the dashboard to export when state is export or absent.
```
