### ISSUE TITLE
Grafana doesn't install latest and can't specify current version

### ISSUE THREAD

**Issue by QCU87Z** [grafana/grafana-ansible-collection#342]
Test playbook fails, if i leave grafana_version as default `latest` it installs _Grafana v10.2.6 (NA)_ which is very not latest.

Not this playbook is running against a virtual machine running Fedora 41.

Does this role work for other people? Also tried to check out the base url that is being used to download the packages it doesn't give a directory listing so can't see if the packages are there.
 
```
- name: Main playbook
  hosts: grafana
  gather_facts: true
  become: true
  roles:
    - grafana.grafana.grafana
  vars:
    grafana_ini:
      security:
        admin_user: admin
        admin_password: admin
    grafana_version: 11.6.0
```

Returns

```
TASK [grafana.grafana.grafana : Install Grafana] ************************************************************************************************
fatal: [192.168.220.85]: FAILED! => {"changed": false, "failures": ["No package grafana-11.6.0 available."], "msg": "Failed to install some of the specified packages", "rc": 1}
```
