### ISSUE TITLE
"Import grafana dashboards via api" task fails in 6.0.1

### ISSUE THREAD

**Issue by jwbensley** [grafana/grafana-ansible-collection#367]
After updating from 5.3.0 to 6.0.1 the task "Import grafana dashboards via api" fails.

The grafana admin password needs to be defined here in the new grafana_ini settings:

```
grafana_ini:
  security:
    admin_user: admin
    admin_password: foo
```

The grafana role will use this info generate the main grafana.ini file just fine, but later in the role when we come to import custom dashboards from JSON files task, the task fails due to auth failure.

[The task "Import grafana dashboards via api"](https://github.com/grafana/grafana-ansible-collection/blob/6.0.1/roles/grafana/tasks/dashboards.yml#L97) expects that `grafana_security` is defined, not `grafana_ini.security`.

Adding `grafana_security` to my vars like the following now blocks the ini config generation from running:

```
grafana_security:
    admin_user: admin
    admin_password: foo

grafana_ini:
  security:
    admin_user: admin
    admin_password: foo
```

However if I use `ansible-playbook --start-at-task "Find dashboards to be provisioned"` to skip the ini generation, then the dashboard auth issues are gone.

Having the admin password defined in two places is not a viable temporary workaround because without the `--start-at-task` option, as I said, the ini generation fails. It fails because of the preflight task ["Check variable types"](https://github.com/grafana/grafana-ansible-collection/blob/6.0.1/roles/grafana/tasks/preflight.yml#L9) expects `grafana_security` to be undefined.

So the dashboard task needs to use `grafana_ini.security` instead of `grafana_security`.
