### ISSUE TITLE
loki_compactor not supported?

### ISSUE THREAD

**Issue by shade-belisar** [grafana/grafana-ansible-collection#372]
I have the following task with which I install loki on my target system:

```
---
  - name: Install Loki via Role
    include_role:
      name: grafana.grafana.loki
    vars:
      loki_version: "{{ versions.loki_version }}"
      loki_limits_config:
        reject_old_samples: true
        reject_old_samples_max_age: 168h
        split_queries_by_interval: 0
        retention_period: 168h
      loki_compactor:
        working_directory: /tmp/loki/retention
        retention_enabled: true
        retention_delete_delay: 2h
        delete_request_store: filesystem
      loki_querier:
        max_concurrent: 20
      loki_query_scheduler:
        max_outstanding_requests_per_tenant: 2048
```
I expected this to limit retention of logs to 7 days. However, I still have logs older than 7 days after installing. I then noticed that in my /etc/loki/config.yaml the compactor does not seem to appear:
```
auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  max_transfer_retries: 0
  wal:
    enabled: True
    dir: /opt/loki/wal

schema_config:
  configs:
    - from: 2018-04-15
      store: boltdb
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 168h

storage_config:
  boltdb:
    directory: /tmp/loki/index

  filesystem:
    directory: /tmp/loki/chunks

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: true
  retention_period: 336h
```
is it not possible to deploy limited retention with this playbook, or am I just misunderstanding something?

**Comment by voidquark** [comment]
Hello @shade-belisar, 

I tested with the latest `v6.0.1` collection, and here’s the result:

- Playbook:
```yaml
---
- name: Install Loki via Role
  hosts: loki
  become: true
  roles:
    - grafana.grafana.loki
  vars:
    loki_limits_config:
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      split_queries_by_interval: 0
      retention_period: 168h
    loki_compactor:
      working_directory: /tmp/loki/retention
      retention_enabled: true
      retention_delete_delay: 2h
      delete_request_store: filesystem
    loki_querier:
      max_concurrent: 20
    loki_query_scheduler:
      max_outstanding_requests_per_tenant: 2048
```

Resulting configuration `/etc/loki/config.yml` includes the `compactor` section:
```yaml
....
compactor:
  working_directory: /tmp/loki/retention
  retention_enabled: true
  retention_delete_delay: 2h
  delete_request_store: filesystem
....
```

I also double-checked the template and didn’t find any issues there.
So it seems likely that the problem is on your end.
