### ISSUE TITLE
Alloy Role: Extra quotes for multi arg CUSTOM_ARGS

### ISSUE THREAD

**Issue by Viv-Rajkumar** [grafana/grafana-ansible-collection#378]
I had alloy setup using a task such as:

```
...
- name: Setup Grafana Alloy
  ansible.builtin.include_role:
    name: grafana.grafana.alloy
  vars:
    alloy_config: "{{ rendered_alloy_config }}"
    alloy_env_file_vars:
      CUSTOM_ARGS: "--server.http.listen-addr=0.0.0.0:12345 --disable-reporting"
```

On running the playbook today, it failed when installing a new binary at an interim state and indicated `... "stderr": "/var/lib/dpkg/info/alloy.prerm: 6: /etc/default/alloy: --disable-reporting: not found\ndpkg: warning: old alloy package pre-removal script subprocess returned error exit status 127 ...`

Saw this in `/etc/default/alloy`

```
cat /etc/default/alloy
# Ansible Managed

CONFIG_FILE="/etc/alloy/config.alloy"
RESTART_ON_UPGRADE=true

CUSTOM_ARGS=--server.http.listen-addr=0.0.0.0:12345 --disable-reporting
```

Could resolve it by wrapping CUSTOM_ARGS with an additional single quote  `CUSTOM_ARGS: '"--server.http.listen-addr=0.0.0.0:12345 --disable-reporting"'`

Thats maybe just expected behavior given the ansible var being `alloy_env_file_vars`.
