### ISSUE TITLE
grafana.grafana.grafana_agent downloads wrong binary

### ISSUE THREAD

**Issue by aWeinzierl** [grafana/grafana-ansible-collection#38]
I am trying to install the grafana agent, however the following playbook installs the `amd64` binary although it should probably pull the `armv6` binary from Github.

`ansible neon -m ansible.builtin.setup -i inventory.yaml | grep "architecture"` prints the actual architecture:
```json
"ansible_architecture": "armv6l",
```

Playbook:
```yaml
---
- hosts: neon
  become: true
  roles:
  - grafana.grafana.grafana_agent
  vars:
    agent_config_local_path: agent-config.yml
```

Verbose logs show:
````json
"url": "https://github.com/grafana/agent/releases/download/v0.29.0/agent-linux-amd64.zip",`
````

Accordingly `sudo journalctl -u grafana-agent` shows:
```
systemd[1]: Started Grafana Agent.
systemd[15197]: grafana-agent.service: Failed to execute /usr/local/bin/agent-linux-amd64: Exec format error
systemd[15197]: grafana-agent.service: Failed at step EXEC spawning /usr/local/bin/agent-linux-amd64: Exec format error
systemd[1]: grafana-agent.service: Main process exited, code=exited, status=203/EXEC
systemd[1]: grafana-agent.service: Failed with result 'exit-code'.
```
