### ISSUE TITLE
possible incomplete example playbook

### ISSUE THREAD

**Issue by goetzk** [grafana/grafana-ansible-collection#39]
hi,

The example playbook `examples/agent-send-to-grafana-cloud.yaml` contains the following vars section:

```
+    grafana_agent_logs_config:
+      global:
+        clients:
+          - url: https://logs-<your region>.grafana.net/loki/api/v1/push
+            basic_auth:
+              username: "1234567"    # your username / instanceID
+              password: "..."   # your grafana.com token
+      scrape_configs:
+        # scrape all of the log files in /var/log on the localhost
+        - job_name: log-files
```

when I run the playbook I see an error 

```
Mar 31 18:13:37 landscape grafana-agent[1540999]: 2023/03/31 18:13:37 error loading config file /etc/grafana-agent/config.yaml: yaml: unmarshal errors:
Mar 31 18:13:37 landscape grafana-agent[1540999]:   line 52: field scrape_configs not found in type logs.config
Mar 31 18:13:37 landscape systemd[1]: grafana-agent.service: Main process exited, code=exited, status=1/FAILURE
Mar 31 18:13:37 landscape systemd[1]: grafana-agent.service: Failed with result 'exit-code'.
```

This example needs the addition of 'configs' as a section to clear up that error and the inclusion of 'positions_directory: "{{ grafana_agent_positions_dir }}"' to match the main configuration and clear up the next error it exposes.

adding a configs section and reflowing the config has cleared up that error
```
grafana_agent_logs_config:
  positions_directory: "{{ grafana_agent_positions_dir }}"
  global:
    clients:
      - url: https://logs-prod-eu-west-0.grafana.net/loki/api/v1/push
        basic_auth:
          username: "123456"    
          # Cloud access token
          password: """
  configs:
    - name: local
      scrape_configs:
        # scrape all of the log files in /var/log on the localhost
        - job_name: log-files
```
