### ISSUE TITLE
Make adding grafana to log-reading group a role option

### ISSUE THREAD

**Issue by goetzk** [grafana/grafana-ansible-collection#40]
Hi,
Just a suggestion:

Following installation I'm seeing a lot of errors about file access, eg
```
Mar 31 18:34:24 landscape grafana-agent[1544236]: ts=2023-03-31T07:34:24.848501667Z caller=filetarget.go:335 level=error component=logs logs_config=local msg="failed to start tailer" error="open /var/log/mail.log: permission denied" filename=/var/log/mail.log
```
This is because those logs are readable by 'adm' group but grafana agent isn't in it. It would be nice if there was a flag to turn on adding grafana to the relevant group, either a bool or a way to specify additional groups grafana should be added to.

thanks
kk

**Comment by goetzk** [comment]
looking at the code i see 'groups' is already used. If grafana_agent_user_group was changed from a string in to a list in defaults/main.yaml it would be possible for administrators to add groups from there.

```
    - name: Add user "{{ grafana_agent_user }}"
      ansible.builtin.user:
        name: "{{ grafana_agent_user }}"
        comment: "Grafana Agent Account"
        groups:
          - "{{ grafana_agent_user_group }}"
        system: true
        shell: "{{ grafana_agent_user_shell }}"
        createhome: "{{ grafana_agent_user_createhome }}"
      when: not __grafana_agent_user_exists and grafana_agent_user != 'root'

```
