### ISSUE TITLE
Agent: extra groups are not added on the next run

### ISSUE THREAD

**Issue by v-zhuravlev** [grafana/grafana-ansible-collection#43]
this block checks that user exists:

```
    - name: Set whether not the user exists
      ansible.builtin.set_fact:
        __grafana_agent_user_exists: "{{ ansible_facts.getent_passwd[grafana_agent_user] is not none }}"

    - name: Add user "{{ grafana_agent_user }}"
      ansible.builtin.user:
        name: "{{ grafana_agent_user }}"
        comment: "Grafana Agent Account"
        groups: "{{ [ grafana_agent_user_group ] + grafana_agent_user_groups }}"
        system: true
        shell: "{{ grafana_agent_user_shell }}"
        createhome: "{{ grafana_agent_user_createhome }}"
      when: not __grafana_agent_user_exists and grafana_agent_user != 'root'

```
If you want to add grafana_user to new `grafana_agent_user_groups` and rerun the playbook, it would not work, as user already exists, so next step would be skipped.

WDYT, about removing __grafana_agent_user_exists set fact alltogether? Ansible would skip next `user` module itself due to its indempotency nature.
