### ISSUE TITLE
grafana agent role doesn't update user groups

### ISSUE THREAD

**Issue by v-zhuravlev** [grafana/grafana-ansible-collection#50]
Updating variable `grafana_agent_user_groups` is ignored if grafana-agent is already installed, so it's not possible to add existing grafana-agent user to new user groups.

This happens due to this check:

in tasks/preflight.yaml:
```
- name: Set whether or not to do the install
  ansible.builtin.set_fact:
    __grafana_agent_do_install: >-
      {{ not __grafana_agent_is_installed.stat.exists or __grafana_agent_installed_version is version_compare(grafana_agent_version, '<') }}

- name: Do install
  ansible.builtin.debug:
    var: __grafana_agent_do_install
```

so user creation/update task is not run (which is a part of install procedure)

I think it's best to remove this check as well, and use ansible native idempotency feature.
