### ISSUE TITLE
Grafana Role - Preflight Domain Check

### ISSUE THREAD

**Issue by pixelrebel** [grafana/grafana-ansible-collection#76]
The following preflight check for the `domain` to `root_url` is backwards. 

https://github.com/grafana/grafana-ansible-collection/blob/main/roles/grafana/tasks/preflight.yml#L45-L50

It checks to see if `root_url` is in `domain`.  But it should be the other way around.  `domain` should be a component of `root_url`.

**Comment by VGerris** [comment]
It seems to me the check itself what you say it doesn't, meaning it does look if domain is part of the root_url.
I do not understand why that is done precisely, since documentation states that the one is part of the other.
It is unclear to me currently if the domain can be different in certain situations, but I think that line should be removed.

A workaround to get the proper values in the eventual /etc/grafana/grafani.ini is to also use this snippet :

```yaml
        grafana_domain: "{{ inventory_hostname }}"
        grafana_url: "https://{{ inventory_hostname }}:3000"
        grafana_server:
          protocol: https
          http_addr: 0.0.0.0
          http_port: 3000
          domain: "{{ inventory_hostname }}"
          enforce_domain: false
          root_url: "https://0.0.0.0:3000"
          # root_url: ''
          cert_key: /etc/grafana/grafana.key
          cert_file: /etc/grafana/grafana.crt
```

How the values are rendered without thet grafana_url setting is a bit of a mystery to me, and I didn't look into it further because this does what I need it to do.

Note that is the http_addr uses the hostname, it will replace it with a resolved IP, so if that IP corresponds to the IP on the interface Grafana should listen on, it will work as well ( I had that set to 127.0.0.1 ).

It would be great if a Grafana dev can respond to the domain / root_url question and clear up documentation.
Thank you!

**Comment by gardar** [comment]
Actually setting the `domain` and `root_url` in the `grafana_server` dict is ignored and has no effect.
These values should be configured with the `grafana_url` and `grafana_domain` variables instead.

https://github.com/grafana/grafana-ansible-collection/blob/fbddddcb983e71e6134b0faece2cebc3c233b4a2/roles/grafana/templates/grafana.ini.j2#L17-L28

**Comment by VGerris** [comment]
> Actually setting the `domain` and `root_url` in the `grafana_server` dict is ignored and has no effect. These values should be configured with the `grafana_url` and `grafana_domain` variables instead.
> 
> https://github.com/grafana/grafana-ansible-collection/blob/fbddddcb983e71e6134b0faece2cebc3c233b4a2/roles/grafana/templates/grafana.ini.j2#L17-L28

That's not the whole story. If those variables are not set, they end up in the configuration anyway, from other parts of the code I presume. Try it out and see what happens when you omit the URL, I think it will use the http_addr.
Would be good to document it precisely, it is unclear to me currently if this is a bug or not. It is unexpected at the minimum.

**Comment by gardar** [comment]
Are you talking about the default values?

https://github.com/grafana/grafana-ansible-collection/blob/fbddddcb983e71e6134b0faece2cebc3c233b4a2/roles/grafana/defaults/main.yml#L37

https://github.com/grafana/grafana-ansible-collection/blob/fbddddcb983e71e6134b0faece2cebc3c233b4a2/roles/grafana/defaults/main.yml#L35

**Comment by VGerris** [comment]
That seems about right. So if nowhere else set, the documentation could be something like:
Grafana grafana_domain and grafana_url values in the [server] section of /etc/grafana/grafana.ini have defaults in main.yml that are used if the values are not set in vars.
( Note that these settings affect on which interface Grafana binds, zo if localhost is one of the automatically filled in vars, one cannot connect to the web interface ).
Thank you for the pointers, can anyone improve the docs? Having this here is already an improvement but some more details that lead to not having to read source code ( which I skipped because the config worked ) has more value.
Thank you

**Comment by gardar** [comment]
Well it's the default behavior in ansible that values are used from `defaults/main.yml` if not overwritten elsewhere.
And there is a comment in the defaults for the `grafana_server` variable which explains this behavior

```yaml
# Additional options for grafana "server" section
# This section WILL omit options for: http_addr, http_port, domain, and root_url, as those settings are set by variables listed before
grafana_server:
  protocol: http
  enforce_domain: false
  socket: ""
  cert_key: ""
  cert_file: ""
  enable_gzip: false
  static_root_path: public
  router_logging: false
  serve_from_sub_path: false
```

But I agree that it would be good to mention this also in the readme, if you want to improve the docs then I'll gladly accept that PR :smiley:
